import { atom } from "recoil";

export const registerState = atom({
  key: "registerState",
  default: {
    cName: null,
    loc1: null,
    loc2: null,
    loc3: null,
    loc4: null,
    locDetail: null,
    phoneNum: null,
    website: null,
    katechX: null,
    katechY: null,
    images: [],
    monOpen: null,
    monClose: null,
    tueOpen: null,
    tueClose: null,
    wedOpen: null,
    wedClose: null,
    thuOpen: null,
    thuClose: null,
    friOpen: null,
    friClose: null,
    satOpen: null,
    satClose: null,
    sunOpen: null,
    sunClose: null,
    recommendation: "",
    socket: null,
    wifi: null,
    restroom: null,
    tableSize: null,
  },
});
