import { atom } from "recoil";

export const registerState = atom({
  key: "registerState",
  default: {
    storeName: "",
    siNm: "",
    sggNm: "",
    rNm: "",
    rNum: "",
    detail: "",
    phone: "",
    website: "",
    lngX: "",
    latY: "",
    imageFiles: [],
    monOpen: "",
    monClose: "",
    tueOpen: "",
    tueClose: "",
    wedOpen: "",
    wedClose: "",
    thuOpen: "",
    thuClose: "",
    friOpen: "",
    friClose: "",
    satOpen: "",
    satClose: "",
    sunOpen: "",
    sunClose: "",
    recommendation: "",
    socket: "",
    wifi: "",
    restroom: "",
    tableSize: "",
    wifiPassword: "",
    etcTime: "",
  },
});
