import { atom } from "recoil";

export const registerState = atom({
  key: "registerState",
  default: {
    storeName: "",
    siNm: null,
    sggNm: null,
    rNm: null,
    rNum: null,
    detail: null,
    phone: null,
    website: null,
    katechX: null,
    katechY: null,
    imageFiles: [],
    monOpen: null,
    monClose: null,
    tueOpen: null,
    tueClose: null,
    wedOpen: null,
    wedClose: null,
    thuOpen: null,
    thuClose: null,
    friOpen: null,
    friClose: null,
    satOpen: null,
    satClose: null,
    sunOpen: null,
    sunClose: null,
    recommendation: "",
    socket: null,
    wifi: null,
    restroom: null,
    tableSize: null,
  },
});
